version: '3'

services:
  db:
    build: ./db
    environment:
      MYSQL_DATABASE: semi1
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: susel
      MYSQL_PASSWORD: 12345
      DATABASE_HOST: db
  web:
    build: ./web
    environment:
      DATABASE_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: semi1
      MYSQL_USER: susel
      MYSQL_PASSWORD: 12345
    ports:
      - "3257:3257"
    depends_on:
      - db
    restart: on-failure 
